# Verlog CHTC Submit File
universe = container
container_image = docker://verlai/verl:vllm012.latest

executable  = verlog.sh

log         = verlog_$(Process).log
output      = verlog_$(Process).out
error       = verlog_$(Process).err

stream_output           = true
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

# Compute resources from train.sbatch
request_cpus            = 4
request_memory          = 200GB
request_disk            = 200GB

# Extra GPU settings
request_gpus            = 4
Requirements            = (Target.CUDADriverVersion >= 12.9)

+WantGPULab = true
+WantFlocking           = false
+WantGlidein            = false
+GPUJobLength           = "short"

queue 1
