# Verlog CHTC Submit File

universe = container
container_image = docker://verlai/verl:vllm012.latest

executable  = verlog.sh
initial_dir = $(results_dir)
arguments   = $(Process) $(Step) $(params)

log         = ../../$(log_dir)/$(Process).log
output      = ../../$(log_dir)/$(Process).out
error       = ../../$(log_dir)/$(Process).err

stream_output           = true
transfer_input_files    = .env, verlog.sh, /home/nbag/data/babyai/, /home/nbag/babyai/
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

# Compute resources from train.sbatch
request_cpus            = 8
request_memory          = 100GB
request_disk            = 100GB

# Extra GPU settings
request_gpus            = 1
Requirements            = (Target.CUDADriverVersion >= 12.1) && (Target.HasCHTCStaging == true)

+WantGPULab             = true
+WantFlocking           = false
+WantGlidein            = false
+GPUJobLength           = "short"

queue 1
